#!/bin/bash 
#### 
# Environment setting script. Automatically generated by Bake
####

if [ "${BASH_SOURCE:-}" == "${0}" ]; then 
    echo "> Call with . bakeSetEnv.sh or source bakeSetEnv.sh" 
    exit 1 
fi 

 export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}/home/hayden/build/lib:/home/hayden/build/lib64"
 export PATH="${PATH:+${PATH}:}/home/hayden/build/bin"
 export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}/home/hayden/bake:/home/hayden/build/lib:/home/hayden/build/lib/python2.7/dist-packages"
